### ISSUE TITLE
Can't load resulting cart in PICO-8

### ISSUE THREAD

**Issue by tobiasvl** [gamax92/midi2pico#1]
The cartridge files produced by `midi2pico` can't be loaded in PICO-8. They seem to be missing the version header information.

```
pico-8 cartridge // http://www.pico-8.com
version 16 -- ?
```

**Comment by tobiasvl** [comment]
Ah, hm, it adds it only if you use the `--stub` argument. That seems like an oversight? I would like to be able to load the cart in PICO-8 to inspect the result even if I don't add the stub gameloop.

**Comment by gamax92** [comment]
Fixed in b2ac56ecd20c9b70c3ac7d7f0bbb9e62d222af52
